### ISSUE TITLE
Maintain old release tags

### ISSUE THREAD

**Issue by kunal546** [code54/buildversion-plugin#11]
When there's a dependency on older version of the plugin and we want to clone the older version using the maven scm tag, it complains that tag does not exist. I see that the tags existed at one point and they were merged and removed. Can we have 1.0.2 tag and maintain the tags in future?

**Comment by dobladez** [comment]
Looks like I just forgot to push all tags. Should be there now:

> $ git tag -l
> v1.0.0
> v1.0.1
> v1.0.2
> v1.0.3
