### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified (com.code54.mojo:buildversion-plugin:1.0.1:set-properties:default:initialize)

### ISSUE THREAD

**Issue by arvidj01** [code54/buildversion-plugin#3]
Not an issue with the plugin but an issue that can affect the plugin.

I was setting up another developers machine from scratch and after importing a working project into eclipse immediately got a:

com.code54.mojo:buildversion-plugin:1.0.1:set-properties failed: java.io.IOException: Cannot run program "git" (in directory "C:\xxx/xxx/xxx/xxx"): CreateProcess error=2, The system cannot find the file specified (com.code54.mojo:buildversion-plugin:1.0.1:set-properties:default:initialize)

error with the pom.xml configuration.

Knowing that (a) the project had worked on the other machine I felt this was not a plugin problem but possibly an issue with the git that had just been installed on the machine.

Opening a command prompt, going to the C:\xxx/xxx/xxx/xxx directory and executing a:

git log --oneline --decorate=short --first-parent

command I saw this as the first line of output form the command ...

"WARNING: terminal is not fully functional"

Looking at the working machine indicated that the version of git was 1.7.11.msysgit.1 while the version on the non-working machines was 1.7.10.msysgit.0. A quick upgrade to mysysgit and everything was fine.

I mention this situation here as it would be the logical place someone would start looking for things that prevent the awesome buildversion-plugin from working.

Please feel free to immediately close this issue.

**Comment by dobladez** [comment]
Thank you for the detailed report.

If it happens again, it'd nice to know if the "WARNING..." line is in stdout or stderr.
