### ISSUE TITLE
Newline at the end of value of build-commit 

### ISSUE THREAD

**Issue by spier** [code54/buildversion-plugin#4]
First things first: Great job, this looks very useful. Just what I needed.

One minor issue I found:

I have create a file that is supposed to contain the output of the variables that are created by your plugin.

The file looks like this:

```
build-commit: ${build-commit}
build-commit-abbrev: ${build-commit-abbrev}
```

After the maven build, the output looks like this:

```
build-commit: bd14e410c7df0fe2f226decbba454dc09996d5bb

build-commit-abbrev: bd14e41
```

So somehow a newline is attached. Any clue why that might happen?
This only happens for the variable **build-commit**.

**Comment by dobladez** [comment]
Could you try with the latest 1.0.2-SNAPSHOT?  Thanks

**Comment by dobladez** [comment]
Release 1.0.2 includes the fix
