### ISSUE TITLE
build-version and build-tag properties do not resolve

### ISSUE THREAD

**Issue by zaro0508** [code54/buildversion-plugin#5]
I was trying out this plugin and i noticed that the build-version and build-tag properties do not get populated with any info.  I used the antrun plugin to print out all of the properties and this is what is shown for the biuld properties when i used the buildversion-plugin.

[echoproperties] build-commit=2fa0869e4b328f7ec4562d5ec8451c8bd1d1aeb7\n
[echoproperties] build-commit-abbrev=2fa0869
[echoproperties] build-tag=N/A
[echoproperties] build-tag-delta=0
[echoproperties] build-tag-lowercase=n/a
[echoproperties] build-tstamp=2013-06-03
[echoproperties] build-version=N/A

-------------------  My pom.xml ----------------------------

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.arch-solutions</groupId>
    <artifactId>play1</artifactId>
    <version>0.0.2-SNAPSHOT</version>
    <scm>
        <connection>scm:git:ssh://github.com/zaro0508/play1.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/zaro0508/play1.git</developerConnection>
        <url>https://github.com/zaro0508/play1</url>
    </scm>

```
<build>
    <plugins>
        <plugin>
            <groupId>com.code54.mojo</groupId>
            <artifactId>buildversion-plugin</artifactId>
            <version>1.0.2</version>
            <executions>
                <execution>
                    <goals>
                        <goal>set-properties</goal>
                    </goals>
                    <configuration>
                        <tstampFormat>yyyy-MM-dd</tstampFormat>
                        <customProperties>
                            { :build-tag-lowercase (clojure.string/lower-case build-tag) }
                        </customProperties>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>1.6</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>run</goal>
                    </goals>
                    <configuration>
                        <target>
                            <property environment="env" />
                            <echoproperties />
                        </target>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

</project>

**Comment by dobladez** [comment]
I guess your project doesn't have any matching tag. From the README:

NOTE: Only tags starting with v are considered, and the v is stripped. Example: 1.2.0-SNAPSHOT (tag on git: v1.2.0-SNAPSHOT)

Cheers,
Fernando
