### ISSUE TITLE
update conch:conch:0.2.1 to me.raynes:conch:0.3.1

### ISSUE THREAD

**Issue by pakore** [code54/buildversion-plugin#6]
The package has changed the group.id and is not available in mvnrepository. 

Now it's available here: http://mvnrepository.com/artifact/me.raynes/conch/0.3.1

I have updated locally the pom and it works ok. It would be nice if you updated your pom.xml so it would work out of the box without having to specify third party repositories (or avoiding to install the library manually).

**Comment by dobladez** [comment]
Thanks.

Now, this removes the dependency on `clojars` repo, however I think we still depend on `oss.sonatype.org`, so it still won't work "out of box".

NOTE: `clojars` may not be needed on runtime, but I'm afraid it is still needed at build time.

**Comment by pakore** [comment]
Actually I see in the repository that the current version is 0.5.1
https://oss.sonatype.org/index.html#nexus-search;quick~conch

By the way, can you release a new version of buildversion-plugin to the nexus repository that has this dependency updated?

**Comment by dobladez** [comment]
1.0.3 released to oss.sonatype.org

**Comment by pakore** [comment]
Thanks, now it gets conch 0.3.1 which is easier to find in other repos.
